-- Ajouter des données dans nos tables 

USE SimpsonsEpisodeGenerator;
GO

INSERT INTO Episodes (SeasonNumber, EpisodeNumber, Title, Description) VALUES

-- Season 1
(1, 1, 'Simpsons Roasting on an Open Fire', 'The Simpsons family prepares for Christmas.'),
(1, 2, 'Bart the Genius', 'Bart swaps IQ tests with Martin Prince.'),
(1, 3, 'Homer''s Odyssey', 'Homer becomes a safety advocate after being fired.'),
(1, 4, 'There''s No Disgrace Like Home', 'Homer tries to improve his family''s behavior.'),
(1, 5, 'Bart the General', 'Bart leads a rebellion against Nelson Muntz.'),
(1, 6, 'Moaning Lisa', 'Lisa feels sad and finds solace in jazz music.'),
(1, 7, 'The Call of the Simpsons', 'The family goes camping and meets a bear.'),
(1, 8, 'The Telltale Head', 'Bart cuts off the head of a statue.'),
(1, 9, 'Life on the Fast Lane', 'Marge gets a bowling ball from Jacques.'),
(1, 10, 'Homer''s Night Out', 'Homer is caught dancing with a belly dancer.'),
(1, 11, 'The Crepes of Wrath', 'Bart is sent to France as an exchange student.'),
(1, 12, 'Krusty Gets Busted', 'Bart discovers Krusty the Clown is not who he seems.'),
(1, 13, 'Some Enchanted Evening', 'The family hires a babysitter with a criminal past.'),

-- Season 2
(2, 1, 'Bart Gets an F', 'Bart struggles to pass a history test.'),
(2, 2, 'Simpson and Delilah', 'Homer gets promoted with miracle hair growth.'),
(2, 3, 'Treehouse of Horror', 'The first Halloween special with three spooky stories.'),
(2, 4, 'Two Cars in Every Garage and Three Eyes on Every Fish', 'Mr. Burns runs for governor after a mutant fish is discovered.'),
(2, 5, 'Dancin'' Homer', 'Homer becomes the Springfield Isotopes mascot.'),
(2, 6, 'Dead Putting Society', 'Bart and Todd Flanders compete in a mini-golf tournament.'),
(2, 7, 'Bart vs. Thanksgiving', 'Bart runs away after ruining Thanksgiving dinner.'),
(2, 8, 'Bart the Daredevil', 'Bart tries to jump Springfield Gorge on his skateboard.'),
(2, 9, 'Itchy & Scratchy & Marge', 'Marge protests cartoon violence.'),
(2, 10, 'Bart Gets Hit by a Car', 'Mr. Burns hits Bart with his car.'),
(2, 11, 'One Fish, Two Fish, Blowfish, Blue Fish', 'Homer eats fugu and believes he has 24 hours to live.'),
(2, 12, 'The Way We Was', 'Homer and Marge recall how they first met.'),
(2, 13, 'Homer vs. Lisa and the 8th Commandment', 'Lisa questions Homer''s stolen cable.'),
(2, 14, 'Principal Charming', 'Skinner falls for Marge''s sister Patty.'),
(2, 15, 'Oh Brother, Where Art Thou?', 'Homer meets his long-lost half-brother Herb.'),
(2, 16, 'Bart''s Dog Gets an F', 'Santa''s Little Helper goes to obedience school.'),
(2, 17, 'Old Money', 'Grampa inherits money and must decide what to do with it.'),
(2, 18, 'Brush with Greatness', 'Marge paints a portrait of Mr. Burns.'),
(2, 19, 'Lisa''s Substitute', 'Lisa bonds with her substitute teacher.'),
(2, 20, 'The War of the Simpsons', 'Homer and Marge attend a marriage retreat.'),
(2, 21, 'Three Men and a Comic Book', 'Bart, Milhouse, and Martin buy a rare comic together.'),
(2, 22, 'Blood Feud', 'Bart saves Mr. Burns with a blood donation.'),

-- Season 3
(3, 1, 'Stark Raving Dad', 'Homer is committed to a mental institution and meets a man who thinks he is Michael Jackson.'),
(3, 2, 'Mr. Lisa Goes to Washington', 'Lisa enters an essay contest and becomes disillusioned with government corruption.'),
(3, 3, 'When Flanders Failed', 'Homer secretly wishes for Ned''s business to fail.'),
(3, 4, 'Bart the Murderer', 'Bart becomes involved with the mob after working at the Legitimate Businessman''s Social Club.'),
(3, 5, 'Homer Defined', 'Homer prevents a meltdown at the power plant by accident.'),
(3, 6, 'Like Father, Like Clown', 'Krusty is reunited with his estranged father.'),
(3, 7, 'Treehouse of Horror II', 'Three more Halloween stories told by the Simpson kids.'),
(3, 8, 'Lisa''s Pony', 'Homer buys Lisa a pony to make her happy.'),
(3, 9, 'Saturdays of Thunder', 'Homer and Bart build a soapbox racer together.'),
(3, 10, 'Flaming Moe''s', 'Moe steals Homer''s drink recipe and becomes famous.'),
(3, 11, 'Burns Verkaufen der Kraftwerk', 'Mr. Burns sells the power plant to German investors.'),
(3, 12, 'I Married Marge', 'Homer recalls his early marriage to Marge.'),
(3, 13, 'Radio Bart', 'Bart tricks Springfield into thinking a boy is trapped in a well.'),
(3, 14, 'Lisa the Greek', 'Lisa picks football winners for Homer.'),
(3, 15, 'Homer Alone', 'Marge takes a vacation, leaving Homer in charge.'),
(3, 16, 'Bart the Lover', 'Bart catfishes his teacher, Mrs. Krabappel.'),
(3, 17, 'Homer at the Bat', 'Mr. Burns hires major league players for the plant''s softball team.'),
(3, 18, 'Separate Vocations', 'Bart becomes hall monitor and Lisa gets discouraged about her future.'),
(3, 19, 'Dog of Death', 'The family struggles to afford surgery for Santa''s Little Helper.'),
(3, 20, 'Colonel Homer', 'Homer becomes the manager of a country singer.'),
(3, 21, 'Black Widower', 'Sideshow Bob tries to kill Selma.'),
(3, 22, 'The Otto Show', 'Otto moves in with the Simpsons after losing his job.'),
(3, 23, 'Bart''s Friend Falls in Love', 'Bart gets jealous when Milhouse gets a girlfriend.'),
(3, 24, 'Brother, Can You Spare Two Dimes?', 'Herb returns and asks Homer for a loan to rebuild his life.'),

-- Season 4
(4, 1, 'Kamp Krusty', 'Bart and Lisa attend a terrible summer camp run by Krusty''s staff.'),
(4, 2, 'A Streetcar Named Marge', 'Marge stars in a musical version of "A Streetcar Named Desire."'),
(4, 3, 'Homer the Heretic', 'Homer skips church and has the best day of his life.'),
(4, 4, 'Lisa the Beauty Queen', 'Lisa enters a beauty pageant after Homer sells her self-esteem.'),
(4, 5, 'Treehouse of Horror III', 'The Simpsons tell three more Halloween tales.'),
(4, 6, 'Itchy & Scratchy: The Movie', 'Bart''s bad behavior gets him banned from seeing the new movie.'),
(4, 7, 'Marge Gets a Job', 'Marge starts working at the nuclear power plant.'),
(4, 8, 'New Kid on the Block', 'Bart falls for his new neighbor, Laura.'),
(4, 9, 'Mr. Plow', 'Homer starts a snow plow business and competes with Barney.'),
(4, 10, 'Lisa''s First Word', 'The family recalls Lisa''s first word.'),
(4, 11, 'Homer''s Triple Bypass', 'Homer needs heart surgery.'),
(4, 12, 'Marge vs. the Monorail', 'Springfield buys a faulty monorail from a conman.'),
(4, 13, 'Selma''s Choice', 'Selma considers having a child after a trip to Duff Gardens.'),
(4, 14, 'Brother from the Same Planet', 'Bart gets a "Big Brother" and Homer gets a "Little Brother."'),
(4, 15, 'I Love Lisa', 'Ralph develops a crush on Lisa after she gives him a Valentine.'),
(4, 16, 'Duffless', 'Homer gives up beer for a month.'),
(4, 17, 'Last Exit to Springfield', 'Homer becomes union leader to save Lisa''s dental plan.'),
(4, 18, 'So It''s Come to This: A Simpsons Clip Show', 'Bart''s prank lands Homer in the hospital.'),
(4, 19, 'The Front', 'Bart and Lisa write scripts for Itchy & Scratchy under Grampa''s name.'),
(4, 20, 'Whacking Day', 'Bart and Lisa try to save snakes from Springfield''s annual event.'),
(4, 21, 'Marge in Chains', 'Marge goes to jail after being accused of shoplifting.'),
(4, 22, 'Krusty Gets Kancelled', 'Krusty''s show is canceled and he plans a comeback.'),

-- Season 5
(5, 1, 'Homer''s Barbershop Quartet', 'Homer tells the story of his time in a barbershop quartet.'),
(5, 2, 'Cape Feare', 'Sideshow Bob is released from prison and seeks revenge on Bart.'),
(5, 3, 'Homer Goes to College', 'Homer goes back to college after failing a nuclear safety test.'),
(5, 4, 'Rosebud', 'Mr. Burns searches for his lost teddy bear, Bobo.'),
(5, 5, 'Treehouse of Horror IV', 'The Simpsons present three Halloween stories.'),
(5, 6, 'Marge on the Lam', 'Marge befriends Ruth Powers and goes on a wild adventure.'),
(5, 7, 'Bart''s Inner Child', 'A self-help guru encourages Springfield to "do what you feel."'),
(5, 8, 'Boy-Scoutz ''n the Hood', 'Bart joins the Junior Campers by accident.'),
(5, 9, 'The Last Temptation of Homer', 'Homer is tempted by a new coworker, Mindy.'),
(5, 10, '$pringfield (or, How I Learned to Stop Worrying and Love Legalized Gambling)', 'Springfield legalizes gambling and Mr. Burns opens a casino.'),
(5, 11, 'Homer the Vigilante', 'Homer leads a vigilante group to catch a cat burglar.'),
(5, 12, 'Bart Gets Famous', 'Bart becomes famous for saying "I didn''t do it."'),
(5, 13, 'Homer and Apu', 'Apu loses his job at the Kwik-E-Mart and moves in with the Simpsons.'),
(5, 14, 'Lisa vs. Malibu Stacy', 'Lisa fights for a feminist doll.'),
(5, 15, 'Deep Space Homer', 'Homer goes to space as a NASA astronaut.'),
(5, 16, 'Homer Loves Flanders', 'Homer becomes friends with Ned Flanders.'),
(5, 17, 'Bart Gets an Elephant', 'Bart wins an elephant named Stampy.'),
(5, 18, 'Burns'' Heir', 'Mr. Burns chooses Bart to be his heir.'),
(5, 19, 'Sweet Seymour Skinner''s Baadasssss Song', 'Bart gets Principal Skinner fired.'),
(5, 20, 'The Boy Who Knew Too Much', 'Bart witnesses an incident but fears telling the truth.'),
(5, 21, 'Lady Bouvier''s Lover', 'Grampa and Marge''s mother start dating.'),
(5, 22, 'Secrets of a Successful Marriage', 'Homer teaches a class and reveals personal secrets.'),

-- Season 6
(6, 1, 'Bart of Darkness', 'Bart breaks his leg and suspects Ned Flanders of murder.'),
(6, 2, 'Lisa''s Rival', 'Lisa meets a new student who outshines her.'),
(6, 3, 'Another Simpsons Clip Show', 'The family recalls stories of love and romance.'),
(6, 4, 'Itchy & Scratchy Land', 'The Simpsons visit a violent cartoon-themed amusement park.'),
(6, 5, 'Sideshow Bob Roberts', 'Sideshow Bob runs for mayor of Springfield.'),
(6, 6, 'Treehouse of Horror V', 'The Simpsons present three new Halloween stories.'),
(6, 7, 'Bart''s Girlfriend', 'Bart falls for Reverend Lovejoy''s daughter, Jessica.'),
(6, 8, 'Lisa on Ice', 'Bart and Lisa compete in hockey.'),
(6, 9, 'Homer Badman', 'Homer is accused of sexual harassment.'),
(6, 10, 'Grampa vs. Sexual Inadequacy', 'Grampa and Homer sell a homemade love tonic.'),
(6, 11, 'Fear of Flying', 'Marge confronts her fear of flying.'),
(6, 12, 'Homer the Great', 'Homer joins a secret society called the Stonecutters.'),
(6, 13, 'And Maggie Makes Three', 'The family remembers Maggie''s birth.'),
(6, 14, 'Bart''s Comet', 'Bart discovers a comet headed for Springfield.'),
(6, 15, 'Homie the Clown', 'Homer becomes a Krusty the Clown impersonator.'),
(6, 16, 'Bart vs. Australia', 'Bart is sent to Australia to apologize for a prank.'),
(6, 17, 'Homer vs. Patty and Selma', 'Homer borrows money from Patty and Selma.'),
(6, 18, 'A Star Is Burns', 'Springfield holds a film festival.'),
(6, 19, 'Lisa''s Wedding', 'A fortune teller predicts Lisa''s future.'),
(6, 20, 'Two Dozen and One Greyhounds', 'Santa''s Little Helper fathers a litter of puppies.'),
(6, 21, 'The PTA Disbands', 'Bart causes chaos when the teachers go on strike.'),
(6, 22, '''Round Springfield', 'Lisa mourns the death of Bleeding Gums Murphy.'),
(6, 23, 'The Springfield Connection', 'Marge becomes a police officer.'),
(6, 24, 'Lemon of Troy', 'Bart and friends defend Springfield''s lemon tree from Shelbyville.'),
(6, 25, 'Who Shot Mr. Burns? (Part One)', 'Mr. Burns is shot and everyone is a suspect.'),

-- Season 7
(7, 1, 'Who Shot Mr. Burns? (Part Two)', 'The mystery of who shot Mr. Burns is solved.'),
(7, 2, 'Radioactive Man', 'A superhero movie is filmed in Springfield.'),
(7, 3, 'Home Sweet Homediddly-Dum-Doodily', 'Bart, Lisa, and Maggie are placed with the Flanders family.'),
(7, 4, 'Bart Sells His Soul', 'Bart sells his soul to Milhouse for $5.'),
(7, 5, 'Lisa the Vegetarian', 'Lisa becomes a vegetarian after meeting Paul and Linda McCartney.'),
(7, 6, 'Treehouse of Horror VI', 'Three more Halloween stories are told.'),
(7, 7, 'King-Size Homer', 'Homer gains weight to work from home.'),
(7, 8, 'Mother Simpson', 'Homer''s mother returns after being presumed dead.'),
(7, 9, 'Sideshow Bob''s Last Gleaming', 'Sideshow Bob threatens Springfield with a nuclear bomb.'),
(7, 10, 'The Simpsons 138th Episode Spectacular', 'Troy McClure hosts a clip show with deleted scenes.'),
(7, 11, 'Marge Be Not Proud', 'Bart gets caught shoplifting a video game.'),
(7, 12, 'Team Homer', 'Homer forms a bowling team.'),
(7, 13, 'Two Bad Neighbors', 'Former President George H.W. Bush moves in across the street.'),
(7, 14, 'Scenes from the Class Struggle in Springfield', 'Marge tries to fit in with the country club crowd.'),
(7, 15, 'Bart the Fink', 'Bart exposes Krusty''s tax fraud.'),
(7, 16, 'Lisa the Iconoclast', 'Lisa investigates Springfield''s founder.'),
(7, 17, 'Homer the Smithers', 'Homer temporarily takes over Smithers'' job.'),
(7, 18, 'The Day the Violence Died', 'Bart and Lisa help the real creator of Itchy & Scratchy.'),
(7, 19, 'A Fish Called Selma', 'Troy McClure marries Selma to boost his career.'),
(7, 20, 'Bart on the Road', 'Bart, Milhouse, Nelson, and Martin take a road trip.'),
(7, 21, '22 Short Films About Springfield', 'The residents of Springfield share interconnected stories.'),
(7, 22, 'Raging Abe Simpson and His Grumbling Grandson in "The Curse of the Flying Hellfish"', 'Grampa and Bart hunt for lost treasure.'),
(7, 23, 'Much Apu About Nothing', 'Apu faces deportation after a referendum on illegal immigrants.'),
(7, 24, 'Homerpalooza', 'Homer joins a music festival sideshow.'),
(7, 25, 'Summer of 4 Ft. 2', 'Lisa reinvents herself during a summer vacation.'),

-- Season 8
(8, 1, 'Treehouse of Horror VII', 'Three more Halloween stories are told.'),
(8, 2, 'You Only Move Twice', 'Homer gets a new job and the family moves to Cypress Creek.'),
(8, 3, 'The Homer They Fall', 'Homer becomes a boxer managed by Moe.'),
(8, 4, 'Burns, Baby Burns', 'Mr. Burns finds his illegitimate son.'),
(8, 5, 'Bart After Dark', 'Bart works at a burlesque house.'),
(8, 6, 'A Milhouse Divided', 'Milhouse''s parents get divorced.'),
(8, 7, 'Lisa''s Date with Density', 'Lisa develops a crush on Nelson.'),
(8, 8, 'Hurricane Neddy', 'A hurricane destroys Ned Flanders'' house.'),
(8, 9, 'El Viaje Misterioso de Nuestro Jomer (The Mysterious Voyage of Homer)', 'Homer eats hot peppers and hallucinates.'),
(8, 10, 'The Springfield Files', 'Homer claims to see an alien in the woods.'),
(8, 11, 'The Twisted World of Marge Simpson', 'Marge opens a pretzel franchise.'),
(8, 12, 'Mountain of Madness', 'The power plant employees get snowed in during a retreat.'),
(8, 13, 'Simpsoncalifragilisticexpiala(Annoyed Grunt)cious', 'The family hires a magical British nanny.'),
(8, 14, 'The Itchy & Scratchy & Poochie Show', 'The producers add Poochie to Itchy & Scratchy.'),
(8, 15, 'Homer''s Phobia', 'Homer befriends a gay man named John.'),
(8, 16, 'Brother from Another Series', 'Sideshow Bob is released from prison and reunited with his brother Cecil.'),
(8, 17, 'My Sister, My Sitter', 'Lisa babysits Bart and Maggie.'),
(8, 18, 'Homer vs. the Eighteenth Amendment', 'Prohibition returns to Springfield.'),
(8, 19, 'Grade School Confidential', 'Principal Skinner and Mrs. Krabappel start dating.'),
(8, 20, 'The Canine Mutiny', 'Bart gets a new dog named Laddie.'),
(8, 21, 'The Old Man and the Lisa', 'Lisa helps Mr. Burns regain his fortune.'),
(8, 22, 'In Marge We Trust', 'Marge becomes the Listen Lady at church.'),
(8, 23, 'Homer''s Enemy', 'Homer clashes with new co-worker Frank Grimes.'),
(8, 24, 'The Simpsons Spin-Off Showcase', 'Three proposed Simpsons spin-off shows are presented.'),
(8, 25, 'The Secret War of Lisa Simpson', 'Lisa and Bart attend military school.'),

-- Season 9
(9, 1, 'The City of New York vs. Homer Simpson', 'Homer must retrieve his car from New York City.'),
(9, 2, 'The Principal and the Pauper', 'Principal Skinner''s real identity is revealed.'),
(9, 3, 'Lisa''s Sax', 'The story of how Lisa got her saxophone is told.'),
(9, 4, 'Treehouse of Horror VIII', 'Three new Halloween stories are presented.'),
(9, 5, 'The Cartridge Family', 'Homer buys a gun for home protection.'),
(9, 6, 'Bart Star', 'Homer becomes coach of Bart''s football team.'),
(9, 7, 'The Two Mrs. Nahasapeemapetilons', 'Apu is pressured into an arranged marriage.'),
(9, 8, 'Lisa the Skeptic', 'Lisa discovers a skeleton that some think is an angel.'),
(9, 9, 'Reality Bites', 'Marge becomes a real estate agent.'),
(9, 10, 'Miracle on Evergreen Terrace', 'Bart ruins Christmas and tries to cover it up.'),
(9, 11, 'All Singing, All Dancing', 'The Simpsons recall their favorite musical numbers.'),
(9, 12, 'Bart Carny', 'Bart and Homer befriend two carnival workers.'),
(9, 13, 'The Joy of Sect', 'The family joins a cult.'),
(9, 14, 'Das Bus', 'The kids are stranded on a desert island.'),
(9, 15, 'The Last Temptation of Krust', 'Krusty changes his act to appeal to a modern audience.'),
(9, 16, 'Dumbbell Indemnity', 'Homer helps Moe commit insurance fraud.'),
(9, 17, 'Lisa the Simpson', 'Lisa fears she is losing her intelligence.'),
(9, 18, 'This Little Wiggy', 'Ralph becomes friends with Bart.'),
(9, 19, 'Simpson Tide', 'Homer joins the Naval Reserve.'),
(9, 20, 'The Trouble with Trillions', 'Homer helps the FBI track down Mr. Burns and a missing trillion-dollar bill.'),
(9, 21, 'Girly Edition', 'Bart and Lisa co-host a kids'' news program.'),
(9, 22, 'Trash of the Titans', 'Homer becomes Springfield''s Sanitation Commissioner.'),
(9, 23, 'King of the Hill', 'Homer trains to climb the Murderhorn mountain.'),
(9, 24, 'Lost Our Lisa', 'Lisa explores Springfield on her own.'),
(9, 25, 'Natural Born Kissers', 'Homer and Marge discover the thrill of public nudity.'),

-- Season 10
(10, 1, 'Lard of the Dance', 'Lisa befriends a new student and Homer tries to sell grease.'),
(10, 2, 'The Wizard of Evergreen Terrace', 'Homer aspires to be an inventor like Thomas Edison.'),
(10, 3, 'Bart the Mother', 'Bart accidentally kills a bird and tries to raise its eggs.'),
(10, 4, 'Treehouse of Horror IX', 'Three new Halloween stories are presented.'),
(10, 5, 'When You Dish Upon a Star', 'Homer befriends Alec Baldwin and Kim Basinger.'),
(10, 6, 'D''oh-in in the Wind', 'Homer discovers his mother''s hippie friends and becomes a hippie himself.'),
(10, 7, 'Lisa Gets an "A"', 'Lisa cheats on a test and feels guilty.'),
(10, 8, 'Homer Simpson in: "Kidney Trouble"', 'Homer must donate a kidney to Grampa.'),
(10, 9, 'Mayored to the Mob', 'Homer becomes Mayor Quimby''s bodyguard.'),
(10, 10, 'Viva Ned Flanders', 'Homer takes Ned to Las Vegas for a wild night.'),
(10, 11, 'Wild Barts Can''t Be Broken', 'Springfield enforces a curfew on kids.'),
(10, 12, 'Sunday, Cruddy Sunday', 'Homer and friends go to the Super Bowl.'),
(10, 13, 'Homer to the Max', 'Homer changes his name after a TV character ruins his reputation.'),
(10, 14, 'I''m with Cupid', 'Apu tries to make the perfect Valentine''s Day for Manjula.'),
(10, 15, 'Marge Simpson in: "Screaming Yellow Honkers"', 'Marge becomes aggressive while driving an SUV.'),
(10, 16, 'Make Room for Lisa', 'Lisa and Homer bond after being forced to share a room.'),
(10, 17, 'Maximum Homerdrive', 'Homer becomes a truck driver.'),
(10, 18, 'Simpsons Bible Stories', 'The family falls asleep in church and dreams biblical tales.'),
(10, 19, 'Mom and Pop Art', 'Homer becomes an outsider artist.'),
(10, 20, 'The Old Man and the "C" Student', 'Bart helps the elderly to avoid repeating the fourth grade.'),
(10, 21, 'Monty Can''t Buy Me Love', 'Mr. Burns tries to become popular.'),
(10, 22, 'They Saved Lisa''s Brain', 'Lisa joins the Springfield chapter of Mensa.'),
(10, 23, 'Thirty Minutes over Tokyo', 'The Simpsons visit Japan.'),

-- Season 11
(11, 1, 'Beyond Blunderdome', 'Homer helps Mel Gibson remake a Hollywood film.'),
(11, 2, 'Brother''s Little Helper', 'Bart is diagnosed with ADD and put on a new drug.'),
(11, 3, 'Guess Who''s Coming to Criticize Dinner?', 'Homer becomes a food critic.'),
(11, 4, 'Treehouse of Horror X', 'Three new Halloween stories are presented.'),
(11, 5, 'E-I-E-I-(Annoyed Grunt)', 'The family grows a hybrid crop called tomacco.'),
(11, 6, 'Hello Gutter, Hello Fadder', 'Homer becomes a bowling celebrity.'),
(11, 7, 'Eight Misbehavin''', 'Apu and Manjula have octuplets.'),
(11, 8, 'Take My Wife, Sleaze', 'Homer and Marge join a motorcycle gang.'),
(11, 9, 'Grift of the Magi', 'A toy company takes over Springfield Elementary before Christmas.'),
(11, 10, 'Little Big Mom', 'Lisa becomes the woman of the house after Marge is hospitalized.'),
(11, 11, 'Faith Off', 'Bart becomes a faith healer.'),
(11, 12, 'The Mansion Family', 'The Simpsons house-sit for Mr. Burns.'),
(11, 13, 'Saddlesore Galactica', 'The family gets a racehorse and faces jockeys who live underground.'),
(11, 14, 'Alone Again, Natura-Diddily', 'Maude Flanders dies in a tragic accident.'),
(11, 15, 'Missionary: Impossible', 'Homer becomes a missionary on a remote island.'),
(11, 16, 'Pygmoelian', 'Moe gets plastic surgery and becomes handsome.'),
(11, 17, 'Bart to the Future', 'A Native American shows Bart his possible future.'),
(11, 18, 'Days of Wine and D''oh''ses', 'Barney quits drinking.'),
(11, 19, 'Kill the Alligator and Run', 'The Simpsons go to Florida for spring break.'),
(11, 20, 'Last Tap Dance in Springfield', 'Lisa takes up tap dancing.'),
(11, 21, 'It''s a Mad, Mad, Mad, Mad Marge', 'Otto''s fiancée moves in with the Simpsons.'),
(11, 22, 'Behind the Laughter', 'A behind-the-scenes look at the Simpsons family.'),

-- Season 12
(12, 1, 'Treehouse of Horror XI', 'Three new Halloween stories are presented.'),
(12, 2, 'A Tale of Two Springfields', 'Springfield is split in two by a new area code.'),
(12, 3, 'Insane Clown Poppy', 'Krusty discovers he has a daughter.'),
(12, 4, 'Lisa the Tree Hugger', 'Lisa joins an environmental group.'),
(12, 5, 'Homer vs. Dignity', 'Homer becomes Mr. Burns'' prank monkey.'),
(12, 6, 'The Computer Wore Menace Shoes', 'Homer creates a gossip website.'),
(12, 7, 'The Great Money Caper', 'Bart and Homer become con artists.'),
(12, 8, 'Skinner''s Sense of Snow', 'A blizzard traps the kids at school.'),
(12, 9, 'HOMR', 'Homer becomes intelligent after removing a crayon from his brain.'),
(12, 10, 'Pokey Mom', 'Marge befriends an ex-convict artist.'),
(12, 11, 'Worst Episode Ever', 'Comic Book Guy has a heart attack and Bart and Milhouse run the store.'),
(12, 12, 'Tennis the Menace', 'The Simpsons build a tennis court and attract tennis stars.'),
(12, 13, 'Day of the Jackanapes', 'Sideshow Bob returns and hypnotizes Bart.'),
(12, 14, 'New Kids on the Blecch', 'Bart joins a boy band that is part of a Navy recruiting plot.'),
(12, 15, 'Hungry, Hungry Homer', 'Homer goes on a hunger strike to keep the Isotopes in Springfield.'),
(12, 16, 'Bye Bye Nerdie', 'Lisa discovers the science behind bullying.'),
(12, 17, 'Simpsons Tall Tales', 'The family tells American tall tales.'),
(12, 18, 'I''m Goin'' to Praiseland', 'The Simpsons and Ned open a Christian theme park.'),
(12, 19, 'Children of a Lesser Clod', 'Homer starts a daycare center.'),
(12, 20, 'Simpsons Tall Tales', 'The family experiences three American legends.'),

-- Season 13
(13, 1, 'Treehouse of Horror XII', 'Three new Halloween stories are presented.'),
(13, 2, 'The Parent Rap', 'Bart and Homer are tethered together as punishment.'),
(13, 3, 'Homer the Moe', 'Moe turns his tavern into a trendy bar.'),
(13, 4, 'A Hunka Hunka Burns in Love', 'Mr. Burns falls in love with a police officer.'),
(13, 5, 'The Blunder Years', 'Homer confronts a childhood trauma.'),
(13, 6, 'She of Little Faith', 'Lisa converts to Buddhism.'),
(13, 7, 'Brawl in the Family', 'A social worker helps the Simpsons resolve family issues.'),
(13, 8, 'Sweets and Sour Marge', 'Marge files a lawsuit against sugar.'),
(13, 9, 'Jaws Wired Shut', 'Homer''s jaw is wired shut after an accident.'),
(13, 10, 'Half-Decent Proposal', 'Artie Ziff returns and asks Marge to spend a weekend with him.'),
(13, 11, 'The Bart Wants What It Wants', 'Bart dates Rainier Wolfcastle''s daughter.'),
(13, 12, 'The Lastest Gun in the West', 'Bart befriends an old cowboy.'),
(13, 13, 'The Old Man and the Key', 'Grampa competes for the affection of a woman at the retirement home.'),
(13, 14, 'Tales from the Public Domain', 'The family stars in famous stories from literature.'),
(13, 15, 'Blame It on Lisa', 'The family travels to Brazil.'),
(13, 16, 'Weekend at Burnsie''s', 'Homer is prescribed medical marijuana.'),
(13, 17, 'Gump Roast', 'The family looks back at their wildest adventures.'),
(13, 18, 'I Am Furious (Yellow)', 'Bart creates an angry comic book character.'),
(13, 19, 'The Sweetest Apu', 'Apu''s affair threatens his marriage.'),
(13, 20, 'Little Girl in the Big Ten', 'Lisa poses as a college student.'),
(13, 21, 'The Frying Game', 'Homer and Marge are accused of murder.'),
(13, 22, 'Poppa''s Got a Brand New Badge', 'Homer becomes Springfield''s police chief.'),

-- Season 14
(14, 1, 'Treehouse of Horror XIII', 'Three new Halloween stories are presented.'),
(14, 2, 'How I Spent My Strummer Vacation', 'Homer attends a rock and roll fantasy camp.'),
(14, 3, 'Bart vs. Lisa vs. the Third Grade', 'Bart and Lisa are placed in the same class.'),
(14, 4, 'Large Marge', 'Marge receives breast implants by mistake.'),
(14, 5, 'Helter Shelter', 'The family lives like it''s 1895.'),
(14, 6, 'The Great Louse Detective', 'Sideshow Bob helps Homer find a mysterious attacker.'),
(14, 7, 'Special Edna', 'Edna Krabappel is nominated for Teacher of the Year.'),
(14, 8, 'The Dad Who Knew Too Little', 'Homer hires a detective to learn more about Lisa.'),
(14, 9, 'The Strong Arms of the Ma', 'Marge becomes a bodybuilder.'),
(14, 10, 'Pray Anything', 'Homer sues the church and wins ownership.'),
(14, 11, 'Barting Over', 'Bart discovers he was once a child star.'),
(14, 12, 'I''m Spelling as Fast as I Can', 'Lisa competes in a spelling bee.'),
(14, 13, 'A Star Is Born-Again', 'Ned Flanders starts dating a movie star.'),
(14, 14, 'Mr. Spritz Goes to Washington', 'Krusty runs for Congress.'),
(14, 15, 'C.E. D''oh', 'Homer becomes a company executive.'),
(14, 16, 'Scuse Me While I Miss the Sky', 'Lisa wants to become an astronomer.'),
(14, 17, 'Three Gays of the Condo', 'Homer moves in with two gay men.'),
(14, 18, 'Dude, Where''s My Ranch?', 'The family vacations at a dude ranch.'),
(14, 19, 'Old Yeller Belly', 'Santa''s Little Helper becomes Duff''s mascot.'),
(14, 20, 'Brake My Wife, Please', 'Homer loses his driver''s license.'),
(14, 21, 'The Bart of War', 'Bart and Milhouse join rival youth groups.'),
(14, 22, 'Moe Baby Blues', 'Moe saves Maggie and becomes attached to her.'),

-- Season 15
(15, 1, 'Treehouse of Horror XIV', 'Three new Halloween stories are presented.'),
(15, 2, 'My Mother the Carjacker', 'Mona Simpson returns to see Homer.'),
(15, 3, 'The President Wore Pearls', 'Lisa becomes student body president.'),
(15, 4, 'The Regina Monologues', 'The Simpsons visit England.'),
(15, 5, 'The Fat and the Furriest', 'Homer is terrorized by a bear and tries to conquer his fear.'),
(15, 6, 'Today I Am a Clown', 'Krusty learns he is not officially Jewish and has a bar mitzvah.'),
(15, 7, '''Tis the Fifteenth Season', 'Homer learns the true meaning of Christmas.'),
(15, 8, 'Marge vs. Singles, Seniors, Childless Couples and Teens, and Gays', 'Springfield is divided over families and non-families.'),
(15, 9, 'I, (Annoyed Grunt)-Bot', 'Homer becomes a robot fighter.'),
(15, 10, 'Diatribe of a Mad Housewife', 'Marge writes a novel based on Homer.'),
(15, 11, 'Margical History Tour', 'The family reenacts moments in world history.'),
(15, 12, 'Milhouse Doesn''t Live Here Anymore', 'Milhouse moves away and Bart befriends Lisa.'),
(15, 13, 'Smart and Smarter', 'Maggie is found to be a genius.'),
(15, 14, 'The Ziff Who Came to Dinner', 'Artie Ziff hides out in the Simpsons'' attic.'),
(15, 15, 'Co-Dependent''s Day', 'Marge and Homer confront their drinking habits.'),
(15, 16, 'The Wandering Juvie', 'Bart is sent to juvenile hall.'),
(15, 17, 'My Big Fat Geek Wedding', 'Edna leaves Skinner at the altar.'),
(15, 18, 'Catch ''Em If You Can', 'The family chases Homer and Marge on a romantic getaway.'),
(15, 19, 'Simple Simpson', 'Homer becomes a masked vigilante.'),
(15, 20, 'The Way We Weren''t', 'Homer and Marge recall a childhood romance.'),
(15, 21, 'Bart-Mangled Banner', 'Bart accidentally moons the American flag.'),
(15, 22, 'Fraudcast News', 'Mr. Burns tries to control all media in Springfield.'),

-- Season 16
(16, 1, 'Treehouse of Horror XV', 'Three new Halloween stories are presented.'),
(16, 2, 'All''s Fair in Oven War', 'Marge enters a baking contest.'),
(16, 3, 'Sleeping with the Enemy', 'Nelson moves in with the Simpsons.'),
(16, 4, 'She Used to Be My Girl', 'Marge''s high school friend is now a news reporter.'),
(16, 5, 'Fat Man and Little Boy', 'Bart starts a business making novelty T-shirts.'),
(16, 6, 'Midnight Rx', 'Homer smuggles prescription drugs from Canada.'),
(16, 7, 'Mommie Beerest', 'Marge becomes a co-owner of Moe''s Tavern.'),
(16, 8, 'Homer and Ned''s Hail Mary Pass', 'Homer and Ned create outrageous Super Bowl halftime shows.'),
(16, 9, 'Pranksta Rap', 'Bart fakes his own kidnapping to attend a rap concert.'),
(16, 10, 'There''s Something About Marrying', 'Springfield legalizes same-sex marriage.'),
(16, 11, 'On a Clear Day I Can''t See My Sister', 'Lisa files a restraining order against Bart.'),
(16, 12, 'Goo Goo Gai Pan', 'The Simpsons travel to China to help Selma adopt a baby.'),
(16, 13, 'Mobile Homer', 'Homer buys an RV and Marge threatens to leave him.'),
(16, 14, 'The Seven-Beer Snitch', 'Marge suspects the new prison is corrupt.'),
(16, 15, 'Future-Drama', 'Bart and Lisa see their future as teenagers.'),
(16, 16, 'Don''t Fear the Roofer', 'Homer befriends a roofer that no one else can see.'),
(16, 17, 'The Heartbroke Kid', 'Bart suffers health problems from junk food.'),
(16, 18, 'A Star Is Torn', 'Lisa enters a singing competition.'),
(16, 19, 'Thank God, It''s Doomsday', 'Homer believes the apocalypse is near.'),
(16, 20, 'Home Away from Homer', 'Flanders moves away after being exploited by college girls.'),
(16, 21, 'The Father, the Son and the Holy Guest Star', 'Bart is expelled and enrolls in a Catholic school.'),

-- Season 17
(17, 1, 'The Bonfire of the Manatees', 'Homer gets into trouble with manatee smugglers.'),
(17, 2, 'The Girl Who Slept Too Little', 'Lisa struggles to sleep after a cemetery moves next door.'),
(17, 3, 'Milhouse of Sand and Fog', 'Homer and Marge nearly divorce after an allergy misunderstanding.'),
(17, 4, 'Treehouse of Horror XVI', 'Three new Halloween stories are presented.'),
(17, 5, 'Marge''s Son Poisoning', 'Marge and Bart spend more time together.'),
(17, 6, 'See Homer Run', 'Homer becomes the "Safety Salamander" to win over voters.'),
(17, 7, 'The Last of the Red Hat Mamas', 'Marge joins a women’s club called the Cheery Red Tomatoes.'),
(17, 8, 'The Italian Bob', 'The Simpsons visit Italy and encounter Sideshow Bob.'),
(17, 9, 'Simpsons Christmas Stories', 'Three Christmas tales are told by the Simpsons.'),
(17, 10, 'Homer''s Paternity Coot', 'Homer suspects Abe may not be his biological father.'),
(17, 11, 'We''re on the Road to D''oh-where', 'Bart and Homer go on a road trip to juvenile detention.'),
(17, 12, 'My Fair Laddy', 'Lisa transforms Groundskeeper Willie into a gentleman.'),
(17, 13, 'The Seemingly Never-Ending Story', 'Lisa tells a complex, nested story.'),
(17, 14, 'Bart Has Two Mommies', 'Marge babysits Rod and Todd while Bart is kidnapped by a chimp.'),
(17, 15, 'Homer Simpson, This Is Your Wife', 'Homer and Marge participate in a wife-swap reality show.'),
(17, 16, 'Million Dollar Abie', 'Grampa becomes a football mascot after a failed assisted suicide.'),
(17, 17, 'Kiss Kiss, Bang Bangalore', 'Homer moves the power plant to India.'),
(17, 18, 'The Wettest Stories Ever Told', 'The family retells historical tales on a cruise.'),
(17, 19, 'Girls Just Want to Have Sums', 'Springfield Elementary separates boys and girls.'),
(17, 20, 'Regarding Margie', 'Marge loses her memory after cleaning the house.'),
(17, 21, 'The Monkey Suit', 'Springfield debates evolution vs. creationism.'),
(17, 22, 'Marge and Homer Turn a Couple Play', 'Homer and Marge help a baseball star save his marriage.'),

-- Season 18
(18, 1, 'The Mook, the Chef, the Wife and Her Homer', 'Lisa befriends Fat Tony''s son.'),
(18, 2, 'Jazzy and the Pussycats', 'Bart becomes a jazz drummer.'),
(18, 3, 'Please Homer, Don''t Hammer ''Em...', 'Homer becomes a carpenter with Marge''s help.'),
(18, 4, 'Treehouse of Horror XVII', 'Three new Halloween stories are presented.'),
(18, 5, 'G.I. (Annoyed Grunt)', 'Bart is sent to military school.'),
(18, 6, 'Moe''n’a Lisa', 'Lisa helps Moe become a poet.'),
(18, 7, 'Ice Cream of Margie (with the Light Blue Hair)', 'Marge starts an ice cream business.'),
(18, 8, 'The Haw-Hawed Couple', 'Bart becomes friends with Nelson.'),
(18, 9, 'Kill Gil, Volumes I & II', 'The Simpsons let Gil stay with them over the holidays.'),
(18, 10, 'The Wife Aquatic', 'The family visits Barnacle Bay.'),
(18, 11, 'Revenge Is a Dish Best Served Three Times', 'The family shares revenge stories.'),
(18, 12, 'Little Big Girl', 'Lisa invents a new identity.'),
(18, 13, 'Springfield Up', 'A documentary filmmaker returns to Springfield.'),
(18, 14, 'Yokel Chords', 'Lisa tutors Cletus'' children.'),
(18, 15, 'Rome-old and Juli-eh', 'Grampa dates Selma.'),
(18, 16, 'Homerazzi', 'Homer becomes a celebrity photographer.'),
(18, 17, 'Marge Gamer', 'Marge becomes addicted to an online game.'),
(18, 18, 'The Boys of Bummer', 'Bart is blamed for losing the championship baseball game.'),
(18, 19, 'Crook and Ladder', 'Homer becomes a volunteer firefighter.'),
(18, 20, 'Stop! Or My Dog Will Shoot', 'Santa''s Little Helper becomes a police dog.'),
(18, 21, '24 Minutes', 'Bart and Lisa try to prevent a school stink bomb attack.'),
(18, 22, 'You Kent Always Say What You Want', 'Kent Brockman is fired after swearing on TV.'),

-- Season 19
(19, 1, 'He Loves to Fly and He D''ohs', 'Homer hires a life coach after flying on Mr. Burns'' private jet.'),
(19, 2, 'The Homer of Seville', 'Homer becomes an opera singer.'),
(19, 3, 'Midnight Towboy', 'Homer becomes a tow truck driver.'),
(19, 4, 'I Don''t Wanna Know Why the Caged Bird Sings', 'Marge is held hostage in a bank robbery.'),
(19, 5, 'Treehouse of Horror XVIII', 'Three new Halloween stories are presented.'),
(19, 6, 'Little Orphan Millie', 'Milhouse''s parents get remarried.'),
(19, 7, 'Husbands and Knives', 'Marge opens a gym for women.'),
(19, 8, 'Funeral for a Fiend', 'Sideshow Bob fakes his own death.'),
(19, 9, 'Eternal Moonshine of the Simpson Mind', 'Homer tries to recover his lost memory.'),
(19, 10, 'E. Pluribus Wiggum', 'Ralph is chosen as a presidential candidate.'),
(19, 11, 'That 90''s Show', 'Homer and Marge recall their life in the 1990s.'),
(19, 12, 'Love, Springfieldian Style', 'Three romantic stories are told on Valentine''s Day.'),
(19, 13, 'The Debarted', 'Bart befriends a new student who is actually a spy for Principal Skinner.'),
(19, 14, 'Dial "N" for Nerder', 'Bart and Lisa think they''ve accidentally killed Martin.'),
(19, 15, 'Smoke on the Daughter', 'Lisa becomes addicted to secondhand smoke while ballet dancing.'),
(19, 16, 'Papa Don''t Leech', 'Lurleen Lumpkin returns and moves in with the Simpsons.'),
(19, 17, 'Apocalypse Cow', 'Bart falls in love with 4-H and befriends a cow.'),
(19, 18, 'Any Given Sundance', 'Lisa makes a documentary about her family.'),
(19, 19, 'Mona Leaves-a', 'Mona Simpson returns and passes away.'),
(19, 20, 'All About Lisa', 'Lisa rises to stardom as Krusty''s sidekick.'),

-- Season 20
(20, 1, 'Sex, Pies and Idiot Scrapes', 'Homer and Flanders become bounty hunters.'),
(20, 2, 'Lost Verizon', 'Bart gets a cell phone and uses it to play pranks.'),
(20, 3, 'Double, Double, Boy in Trouble', 'Bart swaps lives with his wealthy lookalike.'),
(20, 4, 'Treehouse of Horror XIX', 'Three new Halloween stories are presented.'),
(20, 5, 'Dangerous Curves', 'Homer and Marge recall past and present marital problems.'),
(20, 6, 'Homer and Lisa Exchange Cross Words', 'Lisa becomes a crossword puzzle solver.'),
(20, 7, 'MyPods and Boomsticks', 'Lisa befriends a Muslim girl.'),
(20, 8, 'The Burns and the Bees', 'Mr. Burns builds a sports arena, threatening bee populations.'),
(20, 9, 'Lisa the Drama Queen', 'Lisa makes a new friend and they create a fantasy world.'),
(20, 10, 'Take My Life, Please', 'Homer sees what life would be like if he had been class president.'),
(20, 11, 'How the Test Was Won', 'Bart is sent away on the day of a major test.'),
(20, 12, 'No Loan Again, Naturally', 'Flanders buys the Simpsons'' house at auction and becomes their landlord.'),
(20, 13, 'Gone Maggie Gone', 'Maggie is at the center of a town-wide treasure hunt.'),
(20, 14, 'In the Name of the Grandfather', 'The Simpsons travel to Ireland with Grampa.'),
(20, 15, 'Wedding for Disaster', 'Homer and Marge discover their marriage wasn''t legal.'),
(20, 16, 'Eeny Teeny Maya, Moe', 'Moe dates a little person.'),
(20, 17, 'The Good, the Sad and the Drugly', 'Bart falls for a new girl.'),
(20, 18, 'Father Knows Worst', 'Homer becomes a competitive parent.'),
(20, 19, 'Waverly Hills 9-0-2-1-D''oh', 'Homer and Marge rent an apartment in a better school district.'),
(20, 20, 'Four Great Women and a Manicure', 'The women of Springfield tell four stories.'),
(20, 21, 'Coming to Homerica', 'Ogdenvillians migrate to Springfield.'),

-- Season 21
(21, 1, 'Homer the Whopper', 'Comic Book Guy creates a movie based on his superhero alter ego.'),
(21, 2, 'Bart Gets a "Z"', 'Mrs. Krabappel is replaced by a hip new teacher.'),
(21, 3, 'The Great Wife Hope', 'Marge takes up mixed martial arts.'),
(21, 4, 'Treehouse of Horror XX', 'Three new Halloween stories are presented.'),
(21, 5, 'The Devil Wears Nada', 'Marge poses for a charity calendar.'),
(21, 6, 'Pranks and Greens', 'Bart meets the original Springfield prankster.'),
(21, 7, 'Rednecks and Broomsticks', 'Lisa befriends a group of Wiccans.'),
(21, 8, 'Oh Brother, Where Bart Thou?', 'Bart wants a baby brother.'),
(21, 9, 'Thursdays with Abie', 'Grampa''s life stories are published by a reporter.'),
(21, 10, 'Once Upon a Time in Springfield', 'Krusty gets a new female co-host.'),
(21, 11, 'Million Dollar Maybe', 'Homer wins the lottery but hides it from his family.'),
(21, 12, 'Boy Meets Curl', 'The Simpsons form a curling team.'),
(21, 13, 'The Color Yellow', 'Lisa investigates the Simpson family history.'),
(21, 14, 'Postcards from the Wedge', 'Bart discovers he can get away with anything if Homer and Marge fight.'),
(21, 15, 'Stealing First Base', 'Bart kisses a girl at school.'),
(21, 16, 'The Greatest Story Ever D''oh''d', 'Ned and Homer lead a group to Jerusalem.'),
(21, 17, 'American History X-cellent', 'Mr. Burns is sent to prison.'),
(21, 18, 'Chief of Hearts', 'Homer befriends Chief Wiggum.'),
(21, 19, 'The Squirt and the Whale', 'The family tries to save a beached whale.'),
(21, 20, 'To Surveil with Love', 'Springfield installs surveillance cameras everywhere.'),
(21, 21, 'Moe Letter Blues', 'Homer, Reverend Lovejoy, and Apu suspect Moe is after their wives.'),
(21, 22, 'The Bob Next Door', 'Bart discovers Sideshow Bob is his new neighbor.'),
(21, 23, 'Judge Me Tender', 'Moe becomes a judge on a TV talent show.'),

-- Season 22
(22, 1, 'Elementary School Musical', 'Lisa attends a performing arts camp.'),
(22, 2, 'Loan-a Lisa', 'Lisa helps Nelson start a business.'),
(22, 3, 'MoneyBART', 'Lisa becomes Bart''s baseball coach.'),
(22, 4, 'Treehouse of Horror XXI', 'Three new Halloween stories are presented.'),
(22, 5, 'Lisa Simpson, This Isn''t Your Life', 'Lisa wants a better future than Marge''s.'),
(22, 6, 'The Fool Monty', 'Mr. Burns loses his memory and is taken in by the Simpsons.'),
(22, 7, 'How Munched Is That Birdie in the Window?', 'Bart accidentally kills a bird and raises its chicks.'),
(22, 8, 'The Fight Before Christmas', 'Four holiday stories are told.'),
(22, 9, 'Donnie Fatso', 'Homer goes undercover to infiltrate the mob.'),
(22, 10, 'Moms I''d Like to Forget', 'Bart discovers he was in a playgroup as a toddler.'),
(22, 11, 'Flaming Moe', 'Moe and Smithers turn the tavern into a gay bar.'),
(22, 12, 'Homer the Father', 'Homer uses TV wisdom to parent Bart.'),
(22, 13, 'The Blue and the Gray', 'Marge lets her hair go gray.'),
(22, 14, 'Angry Dad: The Movie', 'Bart''s web cartoon is turned into a movie.'),
(22, 15, 'The Scorpion''s Tale', 'Grampa is given a drug to control his temper.'),
(22, 16, 'A Midsummer''s Nice Dream', 'Cheech and Chong visit Springfield.'),
(22, 17, 'Love Is a Many Strangled Thing', 'Bart undergoes therapy for his pranks.'),
(22, 18, 'The Great Simpsina', 'Lisa becomes a magician''s apprentice.'),
(22, 19, 'The Real Housewives of Fat Tony', 'Fat Tony marries Selma.'),
(22, 20, 'Homer Scissorhands', 'Homer becomes a successful hair stylist.'),
(22, 21, '500 Keys', 'The family finds hidden keys all over Springfield.'),
(22, 22, 'The Ned-Liest Catch', 'Edna and Ned begin dating.'),

-- Season 23
(23, 1, 'The Falcon and the D''ohman', 'Homer befriends a new security guard at the plant.'),
(23, 2, 'Bart Stops to Smell the Roosevelts', 'Superintendent Chalmers mentors Bart.'),
(23, 3, 'Treehouse of Horror XXII', 'Three new Halloween stories are presented.'),
(23, 4, 'Replaceable You', 'Bart and Martin create robotic baby seals.'),
(23, 5, 'The Food Wife', 'Marge, Lisa, and Bart become food bloggers.'),
(23, 6, 'The Book Job', 'Homer leads a team to ghostwrite a young adult novel.'),
(23, 7, 'The Man in the Blue Flannel Pants', 'Homer becomes an executive at the power plant.'),
(23, 8, 'The Ten-Per-Cent Solution', 'Krusty teams up with his former agent.'),
(23, 9, 'Holidays of Future Passed', 'A look at the Simpson family in the future.'),
(23, 10, 'Politically Inept, with Homer Simpson', 'Homer becomes a conservative TV pundit.'),
(23, 11, 'The D''oh-cial Network', 'Lisa creates a social network that takes over Springfield.'),
(23, 12, 'Moe Goes from Rags to Riches', 'Moe tells the history of his bar rag.'),
(23, 13, 'The Daughter Also Rises', 'Lisa falls for a new boy at school.'),
(23, 14, 'At Long Last Leave', 'The Simpsons are evicted from Springfield.'),
(23, 15, 'Exit Through the Kwik-E-Mart', 'Bart becomes a graffiti artist.'),
(23, 16, 'How I Wet Your Mother', 'Homer begins wetting the bed.'),
(23, 17, 'Them, Robot', 'Mr. Burns replaces workers with robots.'),
(23, 18, 'Beware My Cheating Bart', 'Bart dates Jimbo''s girlfriend.'),
(23, 19, 'A Totally Fun Thing That Bart Will Never Do Again', 'Bart tries to make a family cruise last forever.'),
(23, 20, 'The Spy Who Learned Me', 'Homer gets a lesson in romance from a movie spy.'),
(23, 21, 'Ned ''N Edna''s Blend', 'Ned and Edna secretly marry.'),
(23, 22, 'Lisa Goes Gaga', 'Lady Gaga visits Springfield.'),

-- Season 24
(24, 1, 'Moonshine River', 'Bart tries to reconnect with Mary Spuckler in New York.'),
(24, 2, 'Treehouse of Horror XXIII', 'Three new Halloween stories are presented.'),
(24, 3, 'Adventures in Baby-Getting', 'Marge wants another baby.'),
(24, 4, 'Gone Abie Gone', 'Grampa goes missing from his retirement home.'),
(24, 5, 'Penny-Wiseguys', 'Homer joins a bowling team run by a mobster.'),
(24, 6, 'A Tree Grows in Springfield', 'Homer becomes obsessed with his new tablet.'),
(24, 7, 'The Day the Earth Stood Cool', 'Hipsters move in next door.'),
(24, 8, 'To Cur with Love', 'Grampa tells the story of his youth and a beloved dog.'),
(24, 9, 'Homer Goes to Prep School', 'Homer becomes a survivalist.'),
(24, 10, 'A Test Before Trying', 'Bart is Springfield Elementary''s last hope on a standardized test.'),
(24, 11, 'The Changing of the Guardian', 'Homer and Marge search for guardians for the kids.'),
(24, 12, 'Love Is a Many-Splintered Thing', 'Bart falls in love with Mary Spuckler again.'),
(24, 13, 'Hardly Kirk-ing', 'Milhouse pretends to be an adult.'),
(24, 14, 'Gorgeous Grampa', 'Grampa has a secret past as a wrestler.'),
(24, 15, 'Black-Eyed, Please', 'Ned Flanders punches Homer.'),
(24, 16, 'Dark Knight Court', 'Bart is accused of pulling a prank during Easter.'),
(24, 17, 'What Animated Women Want', 'Homer tries to improve his marriage.'),
(24, 18, 'Pulpit Friction', 'The Simpsons get a new pastor.'),
(24, 19, 'Whiskey Business', 'Moe gets rich from a new whiskey.'),
(24, 20, 'The Fabulous Faker Boy', 'Bart takes piano lessons to impress a girl.'),
(24, 21, 'The Saga of Carl', 'Carl runs off to Iceland with lottery winnings.'),
(24, 22, 'Dangers on a Train', 'Marge joins a website for married people seeking affairs.'),

-- Season 25
(25, 1, 'Homerland', 'Homer is suspected of being a terrorist after a strange trip.'),
(25, 2, 'Treehouse of Horror XXIV', 'Three new Halloween stories are presented.'),
(25, 3, 'Four Regrettings and a Funeral', 'Springfielders reflect on past regrets.'),
(25, 4, 'YOLO', 'Homer tries to live life to the fullest.'),
(25, 5, 'Labor Pains', 'Homer helps deliver a baby in an elevator.'),
(25, 6, 'The Kid Is All Right', 'Lisa''s new friend is a Republican.'),
(25, 7, 'Yellow Subterfuge', 'Principal Skinner promises a trip on a submarine.'),
(25, 8, 'White Christmas Blues', 'Springfield is the only place with snow for Christmas.'),
(25, 9, 'Steal This Episode', 'Homer learns to download movies illegally.'),
(25, 10, 'Married to the Blob', 'Comic Book Guy gets married.'),
(25, 11, 'Specs and the City', 'Mr. Burns gives out high-tech glasses to his employees.'),
(25, 12, 'Diggs', 'Bart befriends a new student who loves falconry.'),
(25, 13, 'The Man Who Grew Too Much', 'Sideshow Bob becomes a scientist.'),
(25, 14, 'The Winter of His Content', 'Homer bonds with a group of retirees.'),
(25, 15, 'The War of Art', 'The Simpsons buy a painting that may be valuable.'),
(25, 16, 'You Don''t Have to Live Like a Referee', 'Homer becomes a World Cup referee.'),
(25, 17, 'Luca$', 'Lisa dates a boy with dreams of being a competitive eater.'),
(25, 18, 'Days of Future Future', 'A look at the Simpsons in the future.'),
(25, 19, 'What to Expect When Bart''s Expecting', 'Bart becomes an art teacher and accidentally helps a horse get pregnant.'),
(25, 20, 'Brick Like Me', 'The Simpsons wake up in a world made of Lego.'),
(25, 21, 'Pay Pal', 'Marge tries to help Lisa make friends.'),
(25, 22, 'The Yellow Badge of Cowardge', 'Bart cheats to win a school race.'),

-- Season 26
(26, 1, 'Clown in the Dumps', 'A major character dies and Krusty faces a crisis.'),
(26, 2, 'The Wreck of the Relationship', 'Homer and Bart attend a father-son relationship boot camp.'),
(26, 3, 'Super Franchise Me', 'Marge opens a sandwich shop.'),
(26, 4, 'Treehouse of Horror XXV', 'Three new Halloween stories are presented.'),
(26, 5, 'Opposites A-Frack', 'Lisa fights fracking in Springfield.'),
(26, 6, 'Simpsorama', 'The Simpsons meet the cast of Futurama.'),
(26, 7, 'Blazed and Confused', 'Bart faces a new, cruel teacher named Mr. Lassen.'),
(26, 8, 'Covercraft', 'Homer forms a cover band with other dads.'),
(26, 9, 'I Won''t Be Home for Christmas', 'Homer spends Christmas Eve alone.'),
(26, 10, 'The Man Who Came to Be Dinner', 'The Simpsons are abducted by aliens Kang and Kodos.'),
(26, 11, 'Bart''s New Friend', 'Homer becomes best friends with Bart after being hypnotized.'),
(26, 12, 'The Musk Who Fell to Earth', 'Elon Musk arrives in Springfield.'),
(26, 13, 'Walking Big & Tall', 'The town creates a new anthem.'),
(26, 14, 'My Fare Lady', 'Marge becomes a taxi driver.'),
(26, 15, 'The Princess Guide', 'Homer chaperones a Nigerian princess.'),
(26, 16, 'Sky Police', 'The church buys a police plane.'),
(26, 17, 'Waiting for Duffman', 'Homer becomes the new Duffman.'),
(26, 18, 'Peeping Mom', 'Marge spies on Bart when she suspects him of mischief.'),
(26, 19, 'The Kids Are All Fight', 'Bart and Lisa''s childhood rivalry is revealed.'),
(26, 20, 'Let''s Go Fly a Coot', 'Grampa reconnects with old friends.'),
(26, 21, 'Bull-E', 'Bart stands up to bullies with an anti-bullying campaign.'),
(26, 22, 'Mathlete''s Feat', 'Springfield Elementary tries to improve math scores.'),

-- Season 27
(27, 1, 'Every Man''s Dream', 'Homer and Marge separate and explore new relationships.'),
(27, 2, 'Cue Detective', 'Homer and Lisa search for the world''s best barbecue.'),
(27, 3, 'Puffless', 'Patty and Selma try to quit smoking.'),
(27, 4, 'Halloween of Horror', 'Lisa is traumatized by a Halloween event.'),
(27, 5, 'Treehouse of Horror XXVI', 'Three new Halloween stories are presented.'),
(27, 6, 'Friend with Benefit', 'Lisa befriends a rich new student.'),
(27, 7, 'Lisa with an ''S''', 'Lisa goes on tour with a Broadway legend.'),
(27, 8, 'Paths of Glory', 'Lisa tries to prove the existence of a female inventor.'),
(27, 9, 'Barthood', 'A parody of the film "Boyhood" starring Bart.'),
(27, 10, 'The Girl Code', 'Lisa creates an app to predict consequences.'),
(27, 11, 'Teenage Mutant Milk-Caused Hurdles', 'Bart and Lisa go through puberty early.'),
(27, 12, 'Much Apu About Something', 'Apu''s nephew Sanjay opens a rival convenience store.'),
(27, 13, 'Love Is in the N2-O2-Ar-CO2-Ne-He-CH4', 'Professor Frink tries online dating.'),
(27, 14, 'Gal of Constant Sorrow', 'Lisa tries to help a homeless musician.'),
(27, 15, 'Lisa the Veterinarian', 'Lisa volunteers at a veterinary clinic.'),
(27, 16, 'The Marge-ian Chronicles', 'Lisa and Marge compete for a spot on a Mars mission.'),
(27, 17, 'The Burns Cage', 'Smithers comes out as gay to Mr. Burns.'),
(27, 18, 'How Lisa Got Her Marge Back', 'Lisa and Marge bond over music.'),
(27, 19, 'Fland Canyon', 'The Simpsons vacation with the Flanders family.'),
(27, 20, 'To Courier with Love', 'The family travels to Paris with a rare animal.'),
(27, 21, 'Simprovised', 'Homer tries stand-up comedy.'),
(27, 22, 'Orange Is the New Yellow', 'Marge goes to jail after letting Bart play unsupervised.'),

-- Season 28
(28, 1, 'Monty Burns'' Fleeing Circus', 'Mr. Burns finances the reopening of Springfield''s theater.'),
(28, 2, 'Friends and Family', 'Mr. Burns adopts the Simpsons as his virtual family.'),
(28, 3, 'The Town', 'Homer becomes a fan of Boston sports.'),
(28, 4, 'Treehouse of Horror XXVII', 'Three new Halloween stories are presented.'),
(28, 5, 'Trust but Clarify', 'Kent Brockman is fired from his job.'),
(28, 6, 'There Will Be Buds', 'Homer and Kirk Van Houten coach a kids'' lacrosse team.'),
(28, 7, 'Havre de Grace', 'Grampa reunites with an old friend from the army.'),
(28, 8, 'Dad Behavior', 'Homer downloads a fathering app.'),
(28, 9, 'The Last Traction Hero', 'Homer is injured at work and Marge considers a new romance.'),
(28, 10, 'The Nightmare After Krustmas', 'Krusty considers converting to Christianity.'),
(28, 11, 'Pork and Burns', 'The family gives up their possessions, including Spider Pig.'),
(28, 12, 'The Great Phatsby: Part One', 'Mr. Burns is conned by a music mogul.'),
(28, 13, 'The Great Phatsby: Part Two', 'The con against Mr. Burns continues.'),
(28, 14, 'Fatzcarraldo', 'Homer opens a hot dog stand.'),
(28, 15, 'The Cad and the Hat', 'Bart gets a new hat and battles his guilt.'),
(28, 16, 'Kamp Krustier', 'Bart and Lisa are traumatized by their summer camp.'),
(28, 17, '22 for 30', 'Bart becomes a basketball star.'),
(28, 18, 'A Father''s Watch', 'Marge gives Bart a family heirloom.'),
(28, 19, 'Caper Chase', 'Mr. Burns starts his own for-profit university.'),
(28, 20, 'Looking for Mr. Goodbart', 'Bart befriends elderly women for gifts.'),
(28, 21, 'Moho House', 'Mr. Burns tries to break up Homer and Marge.'),
(28, 22, 'Dogtown', 'Dogs take over Springfield.'),

-- Season 29
(29, 1, 'The Serfsons', 'The family lives in a medieval fantasy world.'),
(29, 2, 'Springfield Splendor', 'Lisa and Marge create a graphic novel.'),
(29, 3, 'Whistler''s Father', 'Maggie is revealed to be a whistling prodigy.'),
(29, 4, 'Treehouse of Horror XXVIII', 'Three new Halloween stories are presented.'),
(29, 5, 'Grampy Can Ya Hear Me', 'Grampa gets a hearing aid and becomes a new man.'),
(29, 6, 'The Old Blue Mayor She Ain''t What She Used to Be', 'Marge runs for mayor.'),
(29, 7, 'Singin'' in the Lane', 'Homer and his friends join a bowling league.'),
(29, 8, 'Mr. Lisa''s Opus', 'Lisa''s life is seen through the years.'),
(29, 9, 'Gone Boy', 'Bart is presumed dead after falling down a well.'),
(29, 10, 'Haw-Haw Land', 'Lisa falls for a new boy named Brendan.'),
(29, 11, 'Frink Gets Testy', 'Mr. Burns creates a new intelligence test for Springfield.'),
(29, 12, 'Homer Is Where the Art Isn''t', 'Homer tries to recover a stolen painting.'),
(29, 13, '3 Scenes Plus a Tag from a Marriage', 'Homer and Marge recall their marriage before kids.'),
(29, 14, 'Fears of a Clown', 'Krusty tries to become a serious actor.'),
(29, 15, 'No Good Read Goes Unpunished', 'Marge faces backlash over a book she reads to Lisa.'),
(29, 16, 'King Leer', 'Moe''s family story is revealed.'),
(29, 17, 'Lisa Gets the Blues', 'The family visits New Orleans.'),
(29, 18, 'Forgive and Regret', 'Grampa reveals a long-held secret.'),
(29, 19, 'Left Behind', 'Ned Flanders becomes a teacher.'),
(29, 20, 'Throw Grampa from the Dane', 'The Simpsons go to Denmark for medical care.'),
(29, 21, 'Flanders'' Ladder', 'Bart is haunted by ghosts while in a coma.'),

-- Season 30
(30, 1, 'Bart''s Not Dead', 'Bart claims he went to heaven after a dare.'),
(30, 2, 'Heartbreak Hotel', 'Homer and Marge compete on a reality show.'),
(30, 3, 'My Way or the Highway to Heaven', 'Several characters tell their stories about heaven.'),
(30, 4, 'Treehouse of Horror XXIX', 'Three new Halloween stories are presented.'),
(30, 5, 'Baby You Can''t Drive My Car', 'Homer and Marge work at a tech company.'),
(30, 6, 'From Russia Without Love', 'Bart orders a mail-order bride for Moe.'),
(30, 7, 'Werking Mom', 'Marge becomes a drag performer.'),
(30, 8, 'Krusty the Clown', 'Bart discovers Krusty is teaching at his school.'),
(30, 9, 'Daddicus Finch', 'Lisa starts idolizing Homer.'),
(30, 10, 'Tis the 30th Season', 'The family spends Christmas at a theme park.'),
(30, 11, 'Mad About the Toy', 'Grampa''s history as a model for toy soldiers is revealed.'),
(30, 12, 'The Girl on the Bus', 'Lisa befriends a girl with a perfect family.'),
(30, 13, 'I''m Dancing as Fat as I Can', 'Homer must learn to dance to save his marriage.'),
(30, 14, 'The Clown Stays in the Picture', 'Krusty recalls his time making a movie.'),
(30, 15, '101 Mitigations', 'Comic Book Guy sues Homer.'),
(30, 16, 'I Want You (She''s So Heavy)', 'Homer and Marge compete over a mattress.'),
(30, 17, 'E My Sports', 'Bart joins a competitive gaming team.'),
(30, 18, 'Bart vs. Itchy & Scratchy', 'Bart leads a group of boys against an all-girl reboot.'),
(30, 19, 'Girl''s in the Band', 'Lisa joins a prestigious music academy.'),
(30, 20, 'I''m Just a Girl Who Can''t Say D''oh', 'Marge directs a musical.'),
(30, 21, 'D''oh Canada', 'Lisa becomes a Canadian citizen.'),
(30, 22, 'Woo-Hoo Dunnit?', 'The family investigates the theft of a cake.'),
(30, 23, 'Crystal Blue-Haired Persuasion', 'Marge starts selling crystals.'),

-- Season 31
(31, 1, 'The Winter of Our Monetized Content', 'Homer and Bart become social media stars.'),
(31, 2, 'Go Big or Go Homer', 'Homer mentors a millennial at work.'),
(31, 3, 'The Fat Blue Line', 'Chief Wiggum is framed for a crime he didn''t commit.'),
(31, 4, 'Treehouse of Horror XXX', 'Three new Halloween stories are presented.'),
(31, 5, 'Gorillas on the Mast', 'Bart befriends a depressed sea captain.'),
(31, 6, 'Marge the Lumberjill', 'Marge becomes a competitive lumberjack.'),
(31, 7, 'Livin La Pura Vida', 'The Simpsons vacation in Costa Rica.'),
(31, 8, 'Thanksgiving of Horror', 'Three Thanksgiving-themed horror stories are presented.'),
(31, 9, 'Todd, Todd, Why Hast Thou Forsaken Me?', 'Todd Flanders loses his faith.'),
(31, 10, 'Bobby, It''s Cold Outside', 'Sideshow Bob returns as a mall Santa.'),
(31, 11, 'Hail to the Teeth', 'Marge gets a new smile and Lisa meets a robot double.'),
(31, 12, 'The Miseducation of Lisa Simpson', 'Lisa tries to reform the school''s new STEM curriculum.'),
(31, 13, 'Frinkcoin', 'Professor Frink invents a cryptocurrency.'),
(31, 14, 'Bart the Bad Guy', 'Bart uses movie spoilers for blackmail.'),
(31, 15, 'Screenless', 'The family goes screen-free for a week.'),
(31, 16, 'Better Off Ned', 'Ned Flanders mentors Bart.'),
(31, 17, 'Highway to Well', 'Marge works at a cannabis dispensary.'),
(31, 18, 'The Incredible Lightness of Being a Baby', 'Maggie reunites with baby Hudson.'),
(31, 19, 'Warrin'' Priests', 'A mysterious new preacher comes to town (Part One).'),
(31, 20, 'Warrin'' Priests: Part Two', 'The church struggles with its new preacher.'),
(31, 21, 'The Hateful Eight-Year-Olds', 'Lisa attends a birthday party with rich kids.'),
(31, 22, 'The Way of the Dog', 'Santa''s Little Helper''s traumatic past is revealed.'),

-- Season 32
(32, 1, 'Undercover Burns', 'Mr. Burns goes undercover as an employee.'),
(32, 2, 'I, Carumbus', 'The Simpsons imagine themselves in Ancient Rome.'),
(32, 3, 'Now Museum, Now You Don''t', 'Lisa imagines herself as famous artists.'),
(32, 4, 'Treehouse of Horror XXXI', 'Three new Halloween stories are presented.'),
(32, 5, 'The 7 Beer Itch', 'Homer resists the advances of a British woman.'),
(32, 6, 'Podcast News', 'Grampa is accused of a crime on a true crime podcast.'),
(32, 7, 'Three Dreams Denied', 'Bart becomes a voice actor, Lisa joins band, Comic Book Guy writes a graphic novel.'),
(32, 8, 'The Road to Cincinnati', 'Skinner and Chalmers go to an education convention.'),
(32, 9, 'Sorry Not Sorry', 'Lisa is forced to apologize to Miss Hoover.'),
(32, 10, 'A Springfield Summer Christmas for Christmas', 'Mary Tannenbaum films a Christmas movie in Springfield.'),
(32, 11, 'The Dad-Feelings Limited', 'Comic Book Guy and Kumiko''s love story.'),
(32, 12, 'Diary Queen', 'Bart finds Edna Krabappel''s diary.'),
(32, 13, 'Wad Goals', 'Bart becomes a golf caddy at a country club.'),
(32, 14, 'Yokel Hero', 'Cletus becomes a country music star.'),
(32, 15, 'Do Pizza Bots Dream of Electric Guitars?', 'Homer tries to reunite his old animatronic band.'),
(32, 16, 'Manger Things', 'The family discovers a secret about the first Christmas.'),
(32, 17, 'Uncut Femmes', 'Marge and Sarah Wiggum have a wild adventure.'),
(32, 18, 'Burger Kings', 'The Simpsons start a burger business.'),
(32, 19, 'Panic on the Streets of Springfield', 'Lisa gets an imaginary friend who resembles Morrissey.'),
(32, 20, 'Mother and Child Reunion', 'Lisa envisions her future as a Harvard student.'),
(32, 21, 'The Man from G.R.A.M.P.A.', 'Grampa is recruited by British intelligence.'),
(32, 22, 'The Last Barfighter', 'The barflies become superheroes after a vaccination.'),

-- Season 33
(33, 1, 'The Star of the Backstage', 'Marge revives her high school musical.'),
(33, 2, 'Bart''s in Jail!', 'Grampa is scammed by a fake Bart.'),
(33, 3, 'Treehouse of Horror XXXII', 'Three new Halloween stories are presented.'),
(33, 4, 'The Wayz We Were', 'The kids reunite the parents of their friend.'),
(33, 5, 'Lisa''s Belly', 'Lisa struggles with body image after an offhand comment.'),
(33, 6, 'A Serious Flanders (Part 1)', 'A dark crime saga involving Ned Flanders.'),
(33, 7, 'A Serious Flanders (Part 2)', 'Conclusion of the dark crime saga.'),
(33, 8, 'Portrait of a Lackey on Fire', 'Smithers finds romance with a billionaire.'),
(33, 9, 'Mothers and Other Strangers', 'Homer searches for his mother.'),
(33, 10, 'A Made Maggie', 'Maggie gets baptized by Fat Tony.'),
(33, 11, 'The Longest Marge', 'Marge mentors a female football player.'),
(33, 12, 'Pixelated and Afraid', 'Homer and Marge survive in the wilderness.'),
(33, 13, 'Boyz N the Highlands', 'Bart and friends get lost on a wilderness trek.'),
(33, 14, 'You Won''t Believe What This Episode is About – Act Three Will Shock You!', 'Lisa investigates a conspiracy at the school.'),
(33, 15, 'Bart the Cool Kid', 'Bart becomes popular with the help of a new influencer.'),
(33, 16, 'Pretty Whittle Liar', 'Cletus suspects Brandine of cheating.'),
(33, 17, 'The Sound of Bleeding Gums', 'Lisa helps Bleeding Gums Murphy''s son.'),
(33, 18, 'My Octopus and a Teacher', 'Lisa befriends her substitute teacher.'),
(33, 19, 'Girls Just Shauna Have Fun', 'Shauna mentors Lisa.'),
(33, 20, 'Marge the Meanie', 'Marge reconnects with her childhood as a prankster.'),
(33, 21, 'Meat is Murder', 'The origin story of Moe''s Tavern is revealed.'),
(33, 22, 'Poorhouse Rock', 'Bart learns about class differences.'),

-- Season 34
(34, 1, 'Habeas Tortoise', 'Homer joins a conspiracy group searching for a missing tortoise.'),
(34, 2, 'One Angry Lisa', 'Marge gets hooked on a VR fitness bike.'),
(34, 3, 'Lisa the Boy Scout', 'Lisa and Bart join the Boy Explorers.'),
(34, 4, 'The King of Nice', 'Marge becomes a daytime TV host.'),
(34, 5, 'Not It', 'A parody of Stephen King''s "It".'),
(34, 6, 'Treehouse of Horror XXXIII', 'Three new Halloween stories are presented.'),
(34, 7, 'From Beer to Paternity', 'Duff Man discovers he has a daughter.'),
(34, 8, 'Step Brother from the Same Planet', 'Homer discovers he has a stepbrother.'),
(34, 9, 'When Nelson Met Lisa', 'Lisa and Nelson''s future romance is explored.'),
(34, 10, 'Game Done Changed', 'Lisa becomes an esports coach.'),
(34, 11, 'Top Goon', 'Bart becomes a hockey goon.'),
(34, 12, 'My Life as a Vlog', 'The Simpsons become internet vloggers.'),
(34, 13, 'The Many Saints of Springfield', 'The mob gets involved in little league.'),
(34, 14, 'Carl Carlson Rides Again', 'Carl explores his Icelandic roots.'),
(34, 15, 'Bartless', 'The Simpsons imagine life without Bart.'),
(34, 16, 'Hostile Kirk Place', 'Springfield fights over a new history curriculum.'),
(34, 17, 'Pin Gal', 'Marge joins a bowling league.'),
(34, 18, 'Fan-ily Feud', 'Comic Book Guy creates a viral meme war.'),
(34, 19, 'Write Off This Episode', 'Homer is audited by the IRS.'),
(34, 20, 'The Very Hungry Caterpillars', 'The family battles invasive insects.'),
(34, 21, 'Clown V. Board of Education', 'Krusty opens a clown college.'),
(34, 22, 'Homer''s Crossing', 'Homer becomes a school crossing guard.'),

-- SEASON 35
(35, 1, 'Homer''s Crossing', 'Homer becomes a school crossing guard.'),
(35, 2, 'A Mid-Childhood Night''s Dream', 'Bart enters a gifted program and leaves Lisa behind.'),
(35, 3, 'McMansion & Wife', 'A reality show invades Evergreen Terrace.'),
(35, 4, 'Thirst Trap: A Corporate Love Story', 'Lisa exposes a shady bottled water company.'),
(35, 5, 'Treehouse of Horror XXXIV', 'Three new Halloween stories are presented.'),
(35, 6, 'Iron Marge', 'Marge fights back against an HOA.'),
(35, 7, 'It''s a Blunderful Life', 'Homer is haunted by ghosts of Christmas past.'),
(35, 8, 'Ae Bonny Romance', 'Groundskeeper Willie finds love.'),
(35, 9, 'Murder, She Boat', 'Marge investigates a murder on a river cruise.'),
(35, 10, 'Do the Wrong Thing', 'Lisa tries to make the world a better place.'),
(35, 11, 'Frinkenstein''s Monster', 'Professor Frink creates a monster.'),
(35, 12, 'Lisa Gets an F1', 'Lisa gets involved with Formula 1 racing.'),
(35, 13, 'Clan of the Cave Mom', 'Marge becomes the matriarch of a prehistoric family.'),
(35, 14, 'Night of the Living Wage', 'Marge helps Springfield fight for higher wages.'),
(35, 15, 'Cremains of the Day', 'Homer and friends find a mysterious urn.'),
(35, 16, 'The Tell-Tale Pants', 'Homer tries to hide a secret from Marge.'),
(35, 17, 'The Tipping Point', 'Bart becomes obsessed with tipping.'),
(35, 18, 'Bart''s Brain', 'Bart develops a conscience.'),

-- SEASON 36
(36, 1, 'Bart''s Birthday', 'Bart celebrates a milestone birthday.'),
(36, 2, 'The Yellow Lotus', 'Marge and Lisa join a mysterious flower cult.'),
(36, 3, 'Desperately Seeking Lisa', 'Lisa searches for meaning during a personal crisis.'),
(36, 4, 'Shoddy Heat', 'Homer deals with a summer heatwave.'),
(36, 5, 'Treehouse of Horror XXXV', 'Three new Halloween stories are presented.'),
(36, 6, 'Women in Shorts', 'Springfield holds a women''s empowerment event.'),
(36, 7, 'Treehouse of Horror Presents: Simpsons Wicked This Way Comes', 'The Simpsons present a special Halloween tale.'),
(36, 8, 'Convenience Airways', 'Apu starts a budget airline out of the Kwik-E-Mart.'),
(36, 9, 'Homer and Her Sisters', 'Homer discovers lost siblings.'),
(36, 10, 'The Man Who Flew Too Much', 'Homer becomes obsessed with flying.'),
(36, 11, 'Bottle Episode', 'A single-location episode explores the family''s dynamics.'),
(36, 12, 'The Flandshees of Innersimpson', 'The Flanders and Simpsons families clash.'),
(36, 13, 'The Last Man Expanding', 'Homer competes in a weight loss challenge.'),
(36, 14, 'P.S. I Hate You', 'Lisa and Bart feud over a secret note.'),
(36, 15, 'Abe League of Their Moe', 'Grampa and Moe team up for a new adventure.'),
(36, 16, 'Stew Lies', 'Marge hides a secret recipe from Homer.'),
(36, 17, 'Full Heart, Empty Pool', 'Bart faces a summer with an empty swimming pool.'),
(36, 18, 'Estranger Things', 'A parody of "Stranger Things" in Springfield.');